### ISSUE TITLE
ci: Deploy the LensLend API

### ISSUE THREAD

**Issue by angel-penchev** [KokosTech/lenslend-backend#3]
**Issue type**
I'm submitting a ...

- [ ] bug report
- [ ] feature request
- [ ] testing request
- [ ] documentation request
- [x] CI/CD request
- [ ] question

**Describe the CI/CD change you'd like**
Deploy the LensLend API so it is available to be access by the frontend client.

**Additional context**
If you decide to deploy the API on Vercel, you will need to define a `vercel.json` in your repo root containing the following values:
```
{
  "version": 2,
  "builds": [
    {
      "src": "src/main.ts",
      "use": "@vercel/node"
    }
  ],
  "routes": [
    {
      "src": "/(.*)",
      "dest": "src/main.ts"
    }
  ]
}
```

In addition, if you choose to deploy to Vercel, be aware that there are [several limitations](https://vercel.com/docs/functions/edge-functions/limitations) due to the fact that your app will be deployed as a serverless function.

Alternatively, you can deploy your API locally on your local server or on a cloud provider such as [Digital Ocean](https://docs.digitalocean.com/products/app-platform/how-to/deploy-from-container-images/).

**Comment by KokosTech** [comment]
finished: deployed on heroku @ lenslend-api.kaloyan.tech
